spring.application.name=mini-wallet-backend

# ===============================
# Server Configuration
# ===============================
server.port=${SERVER_PORT}
server.servlet.context-path=${SERVER_CONTEXT_PATH}

# ===============================
# DataSource Configuration
# ===============================
spring.datasource.url=${POSTGRES_DB_URL}
spring.datasource.username=${POSTGRES_DB_USERNAME}
spring.datasource.password=${POSTGRES_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate Configuration 
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Allow circular dependencies if needed
spring.main.allow-circular-references=true

# ===============================
# Logging Configuration 
# ===============================
logging.level.com.miniwallet=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# Application Custom Properties
# ===============================
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=${APP_JWT_EXPIRATION}

